/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.floricultura.telas.produto;

import br.com.floricultura.model.produto.Produto;
import br.com.floricultura.servico.ServicoProduto;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raul.pportela
 */
public class TelaPesquisar extends javax.swing.JInternalFrame {

    CadastrarProduto cadastrarProduto = new CadastrarProduto();

    /**
     * Creates new form TelaPesquisar
     *
     * @throws java.lang.Exception
     */
    public TelaPesquisar() throws Exception {
        initComponents();
        popularTabela(-1);
    }

    public void inicializacaoTela(){
        List<Produto> listaProduto = null;
        try {
            listaProduto = ServicoProduto.listar(); //MONK
           // listaProduto = DaoProduto.listar();   //DAO
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        Produto produto;
        DefaultTableModel dtmListaProduto = (DefaultTableModel) jtProdutos.getModel();
        Object[] dados = new Object[3];
        dtmListaProduto.setRowCount(0);
        int contadorPosicao = 0;

        while (listaProduto != null && contadorPosicao < listaProduto.size()) {
            produto = listaProduto.get(contadorPosicao);
            dados[0] = produto.getIdProduto();
            dados[1] = produto.getProduto();
            dados[2] = produto.getValorUnitario();
            dtmListaProduto.addRow(dados);
            contadorPosicao++;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelProduto = new javax.swing.JPanel();
        lblProduto = new javax.swing.JLabel();
        fieldCodigoProduto = new javax.swing.JTextField();
        TabelaProdutos = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        buttonAlterar = new javax.swing.JButton();
        buttonDeletar = new javax.swing.JButton();
        buttonPesquisar = new javax.swing.JToggleButton();
        buttonCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Produto");

        painelProduto.setBackground(new java.awt.Color(240, 240, 255));

        lblProduto.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblProduto.setText("Codigo Produto");

        fieldCodigoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCodigoProdutoFocusLost(evt);
            }
        });

        jtProdutos.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Categoria", "Valor unitário (R$)", "Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaProdutos.setViewportView(jtProdutos);

        buttonAlterar.setText("Alterar");
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        buttonDeletar.setText("Deletar");
        buttonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletarActionPerformed(evt);
            }
        });

        buttonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa 1.png"))); // NOI18N
        buttonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelProdutoLayout = new javax.swing.GroupLayout(painelProduto);
        painelProduto.setLayout(painelProdutoLayout);
        painelProdutoLayout.setHorizontalGroup(
            painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelProdutoLayout.createSequentialGroup()
                        .addComponent(buttonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAlterar))
                    .addGroup(painelProdutoLayout.createSequentialGroup()
                        .addComponent(fieldCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TabelaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelProdutoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblProduto)
                    .addContainerGap(615, Short.MAX_VALUE)))
        );
        painelProdutoLayout.setVerticalGroup(
            painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelProdutoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabelaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buttonCancelar))
                .addContainerGap())
            .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelProdutoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblProduto)
                    .addContainerGap(355, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisarActionPerformed

        if (fieldCodigoProduto.getText() != null && !fieldCodigoProduto.getText().equals("")) {
            int idProduto = Integer.parseInt(fieldCodigoProduto.getText());
                try {
                    popularTabela(idProduto);
                } catch (Exception ex) {
                    Logger.getLogger(TelaPesquisar.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        }else if(fieldCodigoProduto.getText().equals("")){
            try {
                popularTabela(-1);
            } catch (Exception ex) {
                Logger.getLogger(TelaPesquisar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            try {
                popularTabela(0);
            } catch (Exception ex) {
                Logger.getLogger(TelaPesquisar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonPesquisarActionPerformed

    private void buttonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletarActionPerformed
        if (jtProdutos.getSelectedRow() >= 0) {
            final int row = jtProdutos.getSelectedRow();
            String nome = (String) jtProdutos.getValueAt(row, 1);
            int respostaConfirmacao = JOptionPane.showConfirmDialog(rootPane,
                    "Excluir o produto \"" + nome + "\"?",
                    "Confirmar exclusão", JOptionPane.YES_NO_OPTION);
            if (respostaConfirmacao == JOptionPane.YES_OPTION) {
                int id = (int) jtProdutos.getValueAt(row, 0);
                Produto produto = null;
                try {
                    produto = ServicoProduto.procurarProduto(id);
                } catch (Exception ex) {
                    Logger.getLogger(TelaPesquisar.class.getName()).log(Level.SEVERE, null, ex);
                }
                String resposta = null;
                try {
                    ServicoProduto.excluirProduto(produto.getIdProduto());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                if (resposta == null) {
                    JOptionPane.showMessageDialog(null, "Cliente excluido com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(null, resposta);
                }
            }
        }
    }//GEN-LAST:event_buttonDeletarActionPerformed

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        if (jtProdutos.getSelectedRow() >= 0) {
            final int row = jtProdutos.getSelectedRow();
            int idProduto = (int) jtProdutos.getValueAt(row, 0);
            Produto produto = null;
            try {
                produto = ServicoProduto.procurarProduto(idProduto);
            } catch (Exception ex) {
                Logger.getLogger(TelaPesquisar.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (produto != null) {
                cadastrarProduto.dispose();
                cadastrarProduto = new CadastrarProduto();
                cadastrarProduto.setProduto(produto);
                cadastrarProduto.setModoEdicao(true);
                cadastrarProduto.setTitle("Alterar informações, " + produto.getProduto());
                this.getParent().add(cadastrarProduto);
                cadastrarProduto.setVisible(true);
                cadastrarProduto.toFront();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não foi pré selecionado"
                        + " um produto para edicao",
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void fieldCodigoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCodigoProdutoFocusLost
        if (fieldCodigoProduto.getText() != null && fieldCodigoProduto.getText().length() == 4) {
            buttonPesquisar.setVisible(true);
        }
    }//GEN-LAST:event_fieldCodigoProdutoFocusLost

    public void popularTabela(int idProduto) throws Exception {
        List<Produto> listaProduto = null;

        listaProduto = ServicoProduto.listar();
        Produto produto;

        DefaultTableModel dtmProdutos = (DefaultTableModel) jtProdutos.getModel();
        Object dados[] = new Object[5];
        dtmProdutos.setRowCount(0);

        if (idProduto >= 0) {
            dtmProdutos.setRowCount(0);
            produto = ServicoProduto.procurarProduto(idProduto);
            dtmProdutos.setRowCount(0);
            System.out.println("Nome do produto no popular a tabela> "+ produto.getProduto());
            dados[0] = produto.getIdProduto();
            dados[1] = produto.getProduto();
            dados[2] = produto.getCategoria();
            dados[3] = produto.getValorUnitario();
            dados[4] = produto.getQuantidade();
            dtmProdutos.addRow(dados);
        } else if (idProduto < 0){
            listaProduto = ServicoProduto.listar();
            int contador = 0;
            while (listaProduto != null && contador < listaProduto.size()) {
                produto = listaProduto.get(contador);
                dados[0] = produto.getIdProduto();
                dados[1] = produto.getProduto();
                dados[2] = produto.getCategoria();
                dados[3] = produto.getValorUnitario();
                dados[4] = produto.getQuantidade();
                dtmProdutos.addRow(dados);
                produto=null;
                contador++;
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TabelaProdutos;
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonDeletar;
    private javax.swing.JToggleButton buttonPesquisar;
    private javax.swing.JTextField fieldCodigoProduto;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JPanel painelProduto;
    // End of variables declaration//GEN-END:variables
}
