/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.floricultura.telas.cliente;

import br.com.floricultura.model.cliente.Cliente;
import br.com.floricultura.servico.ServicoCliente;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author raul.pportela
 */
public class IncluirCliente extends javax.swing.JInternalFrame {

    private boolean modoEdicao = false;

    private Cliente cliente = null;

    /**
     * Creates new form CadastroCliente2
     */
    public IncluirCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCliente = new javax.swing.JPanel();
        lblCep = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        lblUfNasc = new javax.swing.JLabel();
        lblEstadoNasc = new javax.swing.JLabel();
        lblUf = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSobrenome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        lblDtNasc = new javax.swing.JLabel();
        lblTelFixo = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblOutroContato = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        fieldCep = new javax.swing.JTextField();
        fieldRua = new javax.swing.JTextField();
        fieldNumero = new javax.swing.JTextField();
        fieldBairro = new javax.swing.JTextField();
        fieldComplemento = new javax.swing.JTextField();
        fieldSobrenome = new javax.swing.JTextField();
        fieldRG = new javax.swing.JTextField();
        fieldOutroContato = new javax.swing.JTextField();
        boxUFNasc = new javax.swing.JComboBox<>();
        boxEstadoNasc = new javax.swing.JComboBox<>();
        boxUF = new javax.swing.JComboBox<>();
        boxEstado = new javax.swing.JComboBox<>();
        boxEstadoCivil = new javax.swing.JComboBox<>();
        buttonSalvar = new javax.swing.JButton();
        boxGenero = new javax.swing.JComboBox<>();
        buttonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldCpf = new javax.swing.JTextField();
        fieldData = new javax.swing.JTextField();
        fieldTelFixo = new javax.swing.JTextField();
        fieldCelular = new javax.swing.JTextField();
        fieldNome = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cliente");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        painelCliente.setBackground(new java.awt.Color(240, 240, 255));

        lblCep.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblCep.setText("CEP");

        lblRua.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblRua.setText("Endereço");

        lblBairro.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblBairro.setText("Bairro");

        lblNumero.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblNumero.setText("Número");

        lblComplemento.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblComplemento.setText("Complemento");

        lblUfNasc.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblUfNasc.setText("UF Nascimento");

        lblEstadoNasc.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblEstadoNasc.setText("Estado Nascimento");

        lblUf.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblUf.setText("UF");

        lblEstado.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblEstado.setText("Estado");

        lblNome.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblNome.setText("Nome");

        lblSobrenome.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblSobrenome.setText("Sobrenome");

        lblCPF.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblCPF.setText("CPF");

        lblRG.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblRG.setText("RG");

        lblSexo.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblSexo.setText("Sexo");

        lblEstadoCivil.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblEstadoCivil.setText("Estado Civil");

        lblDtNasc.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblDtNasc.setText("Data Nascimento");

        lblTelFixo.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblTelFixo.setText("Telefone Fixo");

        lblCelular.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblCelular.setText("Celular");

        lblOutroContato.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblOutroContato.setText("Outro contato");

        lblEmail.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblEmail.setText("E-mail");

        fieldCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCepFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCepFocusLost(evt);
            }
        });

        fieldRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldRuaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldRuaFocusLost(evt);
            }
        });

        fieldNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNumeroFocusLost(evt);
            }
        });

        fieldBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldBairroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldBairroFocusLost(evt);
            }
        });

        fieldSobrenome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldSobrenomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldSobrenomeFocusLost(evt);
            }
        });

        fieldRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldRGFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldRGFocusLost(evt);
            }
        });

        boxUFNasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        boxUFNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxUFNascActionPerformed(evt);
            }
        });

        boxEstadoNasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "ACRE", "ALAGOAS", "AMAPÁ", "AMAZONAS", "BAHIA", "CEARÁ", "DISTRITO FEDERAL", "ESPIRITO SANTO", "GOIÁS", "MARANHÃO", "MATO GROSSO", "MATO GROSSO DO SUL", "MINAS GERAIS", "PARÁ", "PARAÍBA", "PARANÁ", "PERNAMBUCO", "PIAUÍ", "RIO DE JANEIRO", "RIO GRANDE DO NORTE", "RIO GRANDE DO SUL", "RONDÔNIA", "RORAIMA", "SANTA CATARINA", "SÃO PAULO", "SERGIPE", "TOCANTINS" }));

        boxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        boxUF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                boxUFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                boxUFFocusLost(evt);
            }
        });

        boxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "ACRE", "ALAGOAS", "AMAPÁ", "AMAZONAS", "BAHIA", "CEARÁ", "DISTRITO FEDERAL", "ESPIRITO SANTO", "GOIÁS", "MARANHÃO", "MATO GROSSO", "MATO GROSSO DO SUL", "MINAS GERAIS", "PARÁ", "PARAÍBA", "PARANÁ", "PERNAMBUCO", "PIAUÍ", "RIO DE JANEIRO", "RIO GRANDE DO NORTE", "RIO GRANDE DO SUL", "RONDÔNIA", "RORAIMA", "SANTA CATARINA", "SÃO PAULO", "SERGIPE", "TOCANTINS" }));
        boxEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                boxEstadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                boxEstadoFocusLost(evt);
            }
        });

        boxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Solteiro", "Casado", "Divorciado", "Viúvo" }));

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        boxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Masculino", "Feminino" }));
        boxGenero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                boxGeneroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                boxGeneroFocusLost(evt);
            }
        });
        boxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGeneroActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel1.setText("Cadastro de Cliente");

        fieldCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCpfFocusLost(evt);
            }
        });
        fieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCpfActionPerformed(evt);
            }
        });

        fieldData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldDataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldDataFocusLost(evt);
            }
        });
        fieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDataActionPerformed(evt);
            }
        });

        fieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNomeFocusLost(evt);
            }
        });

        jToggleButton1.setText("Preencher");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelClienteLayout = new javax.swing.GroupLayout(painelCliente);
        painelCliente.setLayout(painelClienteLayout);
        painelClienteLayout.setHorizontalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelClienteLayout.createSequentialGroup()
                        .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelClienteLayout.createSequentialGroup()
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDtNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxUFNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUfNasc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEstadoNasc)
                                    .addComponent(boxEstadoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblSexo)
                            .addComponent(lblCPF))
                        .addGap(84, 84, 84))
                    .addGroup(painelClienteLayout.createSequentialGroup()
                        .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelClienteLayout.createSequentialGroup()
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelClienteLayout.createSequentialGroup()
                                        .addComponent(lblNome)
                                        .addGap(161, 161, 161)
                                        .addComponent(lblSobrenome))
                                    .addComponent(jLabel1)
                                    .addGroup(painelClienteLayout.createSequentialGroup()
                                        .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(boxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblUf))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEstado)
                                            .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(painelClienteLayout.createSequentialGroup()
                                        .addComponent(lblBairro)
                                        .addGap(93, 93, 93)
                                        .addComponent(lblComplemento))
                                    .addComponent(lblEmail)
                                    .addGroup(painelClienteLayout.createSequentialGroup()
                                        .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEstadoCivil)
                                            .addGroup(painelClienteLayout.createSequentialGroup()
                                                .addComponent(boxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClienteLayout.createSequentialGroup()
                                .addComponent(buttonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSalvar))
                            .addGroup(painelClienteLayout.createSequentialGroup()
                                .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldSobrenome))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClienteLayout.createSequentialGroup()
                                .addComponent(fieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldComplemento))
                            .addGroup(painelClienteLayout.createSequentialGroup()
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCep))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRua)
                                    .addComponent(fieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelClienteLayout.createSequentialGroup()
                                        .addComponent(lblNumero)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(fieldNumero)))
                            .addGroup(painelClienteLayout.createSequentialGroup()
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelFixo)
                                    .addComponent(fieldTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCelular))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldOutroContato)
                                    .addGroup(painelClienteLayout.createSequentialGroup()
                                        .addComponent(lblOutroContato)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(fieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelClienteLayout.createSequentialGroup()
                                .addComponent(fieldCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelClienteLayout.createSequentialGroup()
                                        .addComponent(lblRG)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(fieldRG, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        painelClienteLayout.setVerticalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblSobrenome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldSobrenome)
                    .addComponent(fieldNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(lblRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldRG)
                    .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(lblEstadoCivil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addGap(15, 15, 15)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtNasc)
                    .addComponent(lblUfNasc)
                    .addComponent(lblEstadoNasc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxUFNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxEstadoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelFixo)
                    .addComponent(lblCelular)
                    .addComponent(lblOutroContato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldOutroContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep)
                    .addComponent(lblRua)
                    .addComponent(lblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(lblComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUf)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonCancelar))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        if (!modoEdicao) {
            cliente = new Cliente();
        } else if (cliente == null) {
            JOptionPane.showMessageDialog(rootPane, "Não foi pré selecionado um cliente"
                    + " para realizar alterações");
            return;
        }
        cliente.setStatusCliente(true);
        cliente.setNome(fieldNome.getText().trim().toUpperCase());
        cliente.setSobrenome(fieldSobrenome.getText().trim().toUpperCase());
        cliente.setCpf(fieldCpf.getText());
        cliente.setRg(fieldRG.getText().trim().toUpperCase());
        cliente.setSexo((String) boxGenero.getSelectedItem());
        cliente.setEstadoCivil((String) boxEstadoCivil.getSelectedItem());
        cliente.setDataNascimento(fieldData.getText());
        cliente.setUfNascimento((String) boxUFNasc.getSelectedItem());
        cliente.setEstadoNascimento((String) boxEstadoNasc.getSelectedItem());
        cliente.setTelefone(fieldTelFixo.getText());
        cliente.setCelular(fieldCelular.getText());
        cliente.setOutroContato(fieldOutroContato.getText());
        cliente.setEmail(fieldEmail.getText().trim().toUpperCase());
        cliente.setCep(fieldCep.getText());
        cliente.setRua(fieldRua.getText().trim().toUpperCase());
        cliente.setNumero(fieldNumero.getText());
        cliente.setBairro(fieldBairro.getText().trim().toUpperCase());
        cliente.setComplemento(fieldComplemento.getText().trim().toUpperCase());
        cliente.setUf((String) boxUF.getSelectedItem());
        cliente.setEstado((String) boxEstado.getSelectedItem());

        String resposta = null;
        if (!modoEdicao) {
            try {
                resposta = ServicoCliente.cadastrarCliente(cliente);
            } catch (Exception ex) {
                Logger.getLogger(IncluirCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            resposta = ServicoCliente.atualizarCliente(cliente);
        }
        if (resposta == null) {
            if (!modoEdicao) {
                JOptionPane.showMessageDialog(null, "Cliente inserido com sucesso");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso");
                this.dispose();
            }

        } else {
            JOptionPane.showMessageDialog(null, resposta);
        }
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void boxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGeneroActionPerformed

    }//GEN-LAST:event_boxGeneroActionPerformed

    private void boxUFNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxUFNascActionPerformed

    }//GEN-LAST:event_boxUFNascActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void fieldCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCpfFocusLost
        if (fieldCpf.getText() != null && fieldCpf.getText().length() == 11) {
            String CPF = fieldCpf.getText();
            String CpfS = "";
            CpfS += CPF.substring(0, 3) + ".";
            CpfS += CPF.substring(3, 6) + ".";
            CpfS += CPF.substring(6, 9) + "-";
            CpfS += CPF.substring(9, 11);
            fieldCpf.setText(CpfS);
        } else if (fieldCpf.getText() != null && (fieldCpf.getText().length() != 11
                && fieldCpf.getText().length() != 14)) {
            fieldCpf.setBorder(new LineBorder(Color.RED));
        }

    }//GEN-LAST:event_fieldCpfFocusLost

    private void fieldRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldRGFocusLost
        if (fieldRG.getText() != null && fieldRG.getText().length() == 9) {
            String RG = fieldRG.getText();
            String RGs = "";
            RGs += RG.substring(0, 2) + ".";
            RGs += RG.substring(2, 5) + ".";
            RGs += RG.substring(5, 8) + "-";
            RGs += RG.substring(8, 9);
            fieldRG.setText(RGs);
        } else if (fieldRG.getText().length() == 10) {
            String RG = fieldRG.getText();
            String RGs = "";
            RGs += RG.substring(0, 2) + ".";
            RGs += RG.substring(2, 5) + ".";
            RGs += RG.substring(5, 8) + "-";
            RGs += RG.substring(8, 10);
            fieldRG.setText(RGs);
        } else if (fieldRG.getText().equals("")) {
            fieldRG.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_fieldRGFocusLost

    private void fieldDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldDataFocusLost
        if (fieldData.getText() != null && fieldData.getText().length() == 8) {
            String dataS = "";
            dataS += fieldData.getText().substring(0, 2) + "/";
            dataS += fieldData.getText().substring(2, 4) + "/";
            dataS += fieldData.getText().substring(4, 8);
            fieldData.setText(dataS);
        } else if (fieldData.getText() != null && (fieldData.getText().length() != 8
                && fieldData.getText().length() != 10)) {
            fieldData.setBorder(new LineBorder(Color.RED));
        }

    }//GEN-LAST:event_fieldDataFocusLost

    private void fieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDataActionPerformed

    private void fieldCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCpfFocusGained
        if (fieldCpf.getText() != null && fieldCpf.getText().length() == 14) {
            String cpf = fieldCpf.getText().substring(0, 3)
                    + fieldCpf.getText().substring(4, 7)
                    + fieldCpf.getText().substring(8, 11)
                    + fieldCpf.getText().substring(12, 14);
            fieldCpf.setBorder(new LineBorder(Color.LIGHT_GRAY));
        } else if (fieldCpf.getText() != null && (fieldCpf.getText().length() < 14
                || fieldCpf.getText().length() > 14)) {
            fieldCpf.setBorder(new LineBorder(Color.LIGHT_GRAY));
        }
    }//GEN-LAST:event_fieldCpfFocusGained

    private void fieldDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldDataFocusGained
        if (fieldData.getText() != null && fieldData.getText().length() != 10) {
            fieldData.setText(null);
            fieldData.setBorder(new LineBorder(Color.LIGHT_GRAY));
        }
    }//GEN-LAST:event_fieldDataFocusGained

    private void fieldCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCepFocusLost
        if (fieldCep.getText() != null && (fieldCep.getText().length() == 8)) {
            String cep = "";
            cep += fieldCep.getText().substring(0, 5) + "-";
            cep += fieldCep.getText().substring(5, 8);
            fieldCep.setText(cep);
        } else if (fieldCep.getText() != null && (fieldCep.getText().length() != 8
                && fieldCep.getText().length() != 9)) {
            fieldCep.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_fieldCepFocusLost

    private void fieldCepFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCepFocusGained
        if (fieldCep.getText() != null && fieldCep.getText().length() != 9) {
            fieldCep.setText(null);
            fieldCep.setBorder(new LineBorder(Color.LIGHT_GRAY));
        }
    }//GEN-LAST:event_fieldCepFocusGained

    private void fieldSobrenomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSobrenomeFocusLost
        if (fieldSobrenome.getText().equals("")) {
            fieldSobrenome.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_fieldSobrenomeFocusLost

    private void fieldSobrenomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSobrenomeFocusGained
        if (fieldSobrenome.getText().equals("")) {
            fieldSobrenome.setBorder(new LineBorder(Color.LIGHT_GRAY));
        }
    }//GEN-LAST:event_fieldSobrenomeFocusGained

    private void fieldRGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldRGFocusGained
        fieldRG.setBorder(new LineBorder(Color.LIGHT_GRAY));
        if (fieldRG.getText() != null && fieldRG.getText().length() == 12) {
            String RG = fieldRG.getText();
            String RGs = "";
            RGs += RG.substring(0, 2)
                    + RG.substring(3, 6)
                    + RG.substring(7, 10)
                    + RG.substring(11, 12);
            fieldRG.setText(RGs);
        } else if (fieldRG.getText().length() == 13) {
            String RG = fieldRG.getText();
            String RGs = "";
            RGs += RGs += RG.substring(0, 2)
                    + RG.substring(3, 6)
                    + RG.substring(7, 10)
                    + RG.substring(11, 13);
            fieldRG.setText(RGs);
        }
    }//GEN-LAST:event_fieldRGFocusGained

    private void fieldRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldRuaFocusLost
        if (fieldRua.getText().equals("")) {
            fieldRua.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_fieldRuaFocusLost

    private void fieldRuaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldRuaFocusGained
        if (fieldRua.getText().equals("")) {
            fieldRua.setBorder(new LineBorder(Color.LIGHT_GRAY));
        }
    }//GEN-LAST:event_fieldRuaFocusGained

    private void fieldNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNumeroFocusLost
        if (fieldNumero.getText().equals("")) {
            fieldNumero.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_fieldNumeroFocusLost

    private void fieldNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNumeroFocusGained
        fieldNumero.setBorder(new LineBorder(Color.LIGHT_GRAY));
    }//GEN-LAST:event_fieldNumeroFocusGained

    private void fieldBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldBairroFocusLost
        if (fieldBairro.getText().equals("")) {
            fieldBairro.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_fieldBairroFocusLost

    private void fieldBairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldBairroFocusGained
        fieldBairro.setBorder(new LineBorder(Color.LIGHT_GRAY));
    }//GEN-LAST:event_fieldBairroFocusGained

    private void boxGeneroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boxGeneroFocusLost
        if (boxGenero.getSelectedItem().equals("Selecione...")) {
            boxGenero.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_boxGeneroFocusLost

    private void boxGeneroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boxGeneroFocusGained
        boxGenero.setBorder(new LineBorder(Color.LIGHT_GRAY));
    }//GEN-LAST:event_boxGeneroFocusGained

    private void boxUFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boxUFFocusLost
        if (boxUF.getSelectedItem().equals("Selecione...")) {
            boxUF.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_boxUFFocusLost

    private void boxUFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boxUFFocusGained
        boxUF.setBorder(new LineBorder(Color.LIGHT_GRAY));
    }//GEN-LAST:event_boxUFFocusGained

    private void boxEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boxEstadoFocusLost
        if (boxEstado.getSelectedItem().equals("Selecione...")) {
            boxEstado.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_boxEstadoFocusLost

    private void boxEstadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boxEstadoFocusGained
        boxEstado.setBorder(new LineBorder(Color.LIGHT_GRAY));
    }//GEN-LAST:event_boxEstadoFocusGained

    private void fieldNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNomeFocusGained
        fieldNome.setBorder(new LineBorder(Color.LIGHT_GRAY));
    }//GEN-LAST:event_fieldNomeFocusGained

    private void fieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNomeFocusLost
        if (fieldNome.getText().equals("")) {
            fieldNome.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_fieldNomeFocusLost

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        if (modoEdicao && cliente != null) {
            fieldNome.setText(cliente.getNome());
            fieldSobrenome.setText(cliente.getSobrenome());
            String cpfPontuado = "";
            cpfPontuado += cliente.getCpf().substring(0, 3) + ".";
            cpfPontuado += cliente.getCpf().substring(3, 6) + ".";
            cpfPontuado += cliente.getCpf().substring(6, 9) + "-";
            cpfPontuado += cliente.getCpf().substring(9, 11);
            fieldCpf.setText(cpfPontuado);
            fieldRG.setText(cliente.getRg());
            for (int i = 0; i <= 2; i++) {
                if (boxGenero.getItemAt(i).equals(cliente.getSexo())) {
                    boxGenero.setSelectedIndex(i);
                    break;
                }
            }
            for (int i = 0; i <= 4; i++) {
                if (boxEstadoCivil.getItemAt(i).equals(cliente.getEstadoCivil())) {
                    boxEstadoCivil.setSelectedIndex(i);
                    break;
                }
            }
            fieldData.setText(cliente.getDataNascimento());
            for (int i = 0; i <= 28; i++) {
                if (boxUFNasc.getItemAt(i).equals(cliente.getUfNascimento())) {
                    boxUFNasc.setSelectedIndex(i);
                    break;
                }
            }
            for (int i = 0; i <= 28; i++) {
                if (boxEstadoNasc.getItemAt(i).equals(cliente.getEstadoNascimento())) {
                    boxEstadoNasc.setSelectedIndex(i);
                    break;
                }
            }
            fieldTelFixo.setText(cliente.getTelefone());
            fieldCelular.setText(cliente.getCelular());
            fieldOutroContato.setText(cliente.getOutroContato());
            fieldEmail.setText(cliente.getEmail());
            fieldCep.setText(cliente.getCep());
            fieldRua.setText(cliente.getRua());
            fieldNumero.setText(cliente.getNumero());
            fieldBairro.setText(cliente.getBairro());
            fieldComplemento.setText(cliente.getComplemento());
            for (int i = 0; i <= 28; i++) {
                if (boxUF.getItemAt(i).equals(cliente.getUf())) {
                    boxUF.setSelectedIndex(i);
                    break;
                }
            }
            for (int i = 0; i <= 28; i++) {
                if (boxEstado.getItemAt(i).equals(cliente.getEstado())) {
                    boxEstado.setSelectedIndex(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void fieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCpfActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        fieldNome.setText("Raul");
        fieldSobrenome.setText("de Paula");
        fieldCpf.setText("442.784.298-43");
        fieldRG.setText("39.752.412-2");
        fieldCep.setText("04856-700");
        fieldRua.setText("Rua pedra mineira");
        fieldNumero.setText("09");
        fieldBairro.setText("Jardim das Pedras");
        fieldData.setText("03/10/1996");
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEstado;
    private javax.swing.JComboBox<String> boxEstadoCivil;
    private javax.swing.JComboBox<String> boxEstadoNasc;
    private javax.swing.JComboBox<String> boxGenero;
    private javax.swing.JComboBox<String> boxUF;
    private javax.swing.JComboBox<String> boxUFNasc;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JTextField fieldBairro;
    private javax.swing.JTextField fieldCelular;
    private javax.swing.JTextField fieldCep;
    private javax.swing.JTextField fieldComplemento;
    private javax.swing.JTextField fieldCpf;
    private javax.swing.JTextField fieldData;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldNumero;
    private javax.swing.JTextField fieldOutroContato;
    private javax.swing.JTextField fieldRG;
    private javax.swing.JTextField fieldRua;
    private javax.swing.JTextField fieldSobrenome;
    private javax.swing.JTextField fieldTelFixo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblDtNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblEstadoNasc;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblOutroContato;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTelFixo;
    private javax.swing.JLabel lblUf;
    private javax.swing.JLabel lblUfNasc;
    private javax.swing.JPanel painelCliente;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the modoEdicao
     */
    public boolean isModoEdicao() {
        return modoEdicao;
    }

    /**
     * @return the cliente
     */
    public Cliente getCliente() {
        return cliente;
    }

    /**
     * @param cliente the cliente to set
     */
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    /**
     * @param modoEdicao the modoEdicao to set
     */
    public void setModoEdicao(boolean modoEdicao) {
        this.modoEdicao = modoEdicao;
    }
}
