/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.floricultura.telas.cliente;

import br.com.floricultura.model.cliente.Cliente;
import br.com.floricultura.servico.ServicoCliente;
import br.com.floricultura.telas.vendas.TelaVenda;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raul.pportela
 */
public class PesquisarCliente extends javax.swing.JInternalFrame {

    IncluirCliente incluirCliente = new IncluirCliente();

    public PesquisarCliente() throws Exception {
        initComponents();
        popularTabela(null);
    }

    private void popularTabela(String cpf) throws Exception {

        List<Cliente> listaClientes = null;
        try {
            listaClientes = ServicoCliente.listar();
        } catch (Exception ex) {
            Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        Cliente clienteC;
        DefaultTableModel dtmClientes = (DefaultTableModel) jTableClientesCadsatrados.getModel();
        Object[] dados = new Object[6];
        dtmClientes.setRowCount(0);
        if (cpf != null && !cpf.equals("")) {
            dtmClientes.setRowCount(0);
            clienteC = ServicoCliente.procurarCliente(cpf);
            dados[0] = clienteC.getIdCliente();
            dados[1] = clienteC.getNome() + " " + clienteC.getSobrenome();
            dados[2] = clienteC.getCpf();
            dados[3] = clienteC.getRua() + ", " + clienteC.getNumero() + " - "
                    + clienteC.getBairro() + " - " + clienteC.getUf() + " - " + clienteC.getEstado();
            dados[4] = clienteC.getTelefone() + " - " + clienteC.getCelular();
            dados[5] = clienteC.getEmail();
            dtmClientes.addRow(dados);
        } else {
            dtmClientes.setRowCount(0);
            int contadorPosicao = 0;
            while (listaClientes != null && contadorPosicao < listaClientes.size()) {
                clienteC = listaClientes.get(contadorPosicao);
                dados[0] = clienteC.getIdCliente();
                dados[1] = clienteC.getNome() + " " + clienteC.getSobrenome();
                dados[2] = clienteC.getCpf();
                dados[3] = clienteC.getRua() + ", " + clienteC.getNumero() + " - "
                        + clienteC.getBairro() + " - " + clienteC.getUf() + " - " + clienteC.getEstado();
                dados[4] = clienteC.getTelefone() + " - " + clienteC.getCelular();
                dados[5] = clienteC.getEmail();
                dtmClientes.addRow(dados);
                contadorPosicao++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabelaCliente = new javax.swing.JScrollPane();
        jTableClientesCadsatrados = new javax.swing.JTable();
        lblPesquisaClientes = new javax.swing.JLabel();
        lblCpfPesquisa = new javax.swing.JLabel();
        buttonPesquisa = new javax.swing.JToggleButton();
        buttonAlterar = new javax.swing.JButton();
        buttonDeletar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        fieldCpf = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cliente");

        jPanel1.setBackground(new java.awt.Color(240, 240, 255));

        jTableClientesCadsatrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome Completo", "CPF", "Endereço", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelaCliente.setViewportView(jTableClientesCadsatrados);
        if (jTableClientesCadsatrados.getColumnModel().getColumnCount() > 0) {
            jTableClientesCadsatrados.getColumnModel().getColumn(0).setMinWidth(40);
            jTableClientesCadsatrados.getColumnModel().getColumn(0).setMaxWidth(40);
            jTableClientesCadsatrados.getColumnModel().getColumn(2).setMinWidth(60);
            jTableClientesCadsatrados.getColumnModel().getColumn(2).setMaxWidth(80);
            jTableClientesCadsatrados.getColumnModel().getColumn(4).setMinWidth(80);
            jTableClientesCadsatrados.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        lblPesquisaClientes.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        lblPesquisaClientes.setText("Pesquisa de Clientes");

        lblCpfPesquisa.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblCpfPesquisa.setText("CPF de Pesquisa");

        buttonPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa 1.png"))); // NOI18N
        buttonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisaActionPerformed(evt);
            }
        });

        buttonAlterar.setText("Alterar");
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        buttonDeletar.setText("Deletar");
        buttonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        fieldCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCpfFocusLost(evt);
            }
        });
        fieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCpfPesquisa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(buttonCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonDeletar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonAlterar))
                        .addComponent(TabelaCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPesquisaClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPesquisaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblCpfPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TabelaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAlterar)
                    .addComponent(buttonDeletar)
                    .addComponent(buttonCancelar))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisaActionPerformed
        if (fieldCpf.getText() != null && !fieldCpf.getText().equals("")) {
            try {
                String cpf = "";
            cpf += fieldCpf.getText().substring(0, 3)
                    + fieldCpf.getText().substring(4, 7)
                    + fieldCpf.getText().substring(8, 11)
                    + fieldCpf.getText().substring(12, 14);
                popularTabela(cpf);
            } catch (Exception ex) {
                Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(fieldCpf.getText().equals("")) {
            try {
                popularTabela(null);
            } catch (Exception ex) {
                Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (fieldCpf.getText().length() != 14){
            JOptionPane.showMessageDialog(rootPane, "Numero de CPF Inválido.");
        }
        else {
            try {
                popularTabela(null);
            } catch (Exception ex) {
                Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_buttonPesquisaActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void fieldCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCpfFocusGained
        buttonPesquisa.setEnabled(true);
        if (fieldCpf.getText() != null && fieldCpf.getText().length() != 14) {
            fieldCpf.setText(null);
            fieldCpf.setBorder(new LineBorder(Color.LIGHT_GRAY));
        }
    }//GEN-LAST:event_fieldCpfFocusGained

    private void fieldCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCpfFocusLost
        if (fieldCpf.getText().length() == 11) {
            String CPF = fieldCpf.getText();
            String CpfS = "";
            CpfS += CPF.substring(0, 3) + ".";
            CpfS += CPF.substring(3, 6) + ".";
            CpfS += CPF.substring(6, 9) + "-";
            CpfS += CPF.substring(9, 11);
            fieldCpf.setText(CpfS);
        } else if (fieldCpf.getText() != null && (fieldCpf.getText().length() > 11
                || fieldCpf.getText().length() < 11)) {
            fieldCpf.setBorder(new LineBorder(Color.RED));
        } 
    }//GEN-LAST:event_fieldCpfFocusLost

    private void buttonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletarActionPerformed

        if (jTableClientesCadsatrados.getSelectedRow() >= 0) {
            final int row = jTableClientesCadsatrados.getSelectedRow();
            String nome = (String) jTableClientesCadsatrados.getValueAt(row, 1);
            int respostaConfirmacao = JOptionPane.showConfirmDialog(rootPane,
                    "Excluir o cliente \"" + nome + "\"?",
                    "Confirmar exclusão", JOptionPane.YES_NO_OPTION);
            if (respostaConfirmacao == JOptionPane.YES_OPTION) {
                String cpf = (String) jTableClientesCadsatrados.getValueAt(row, 2);
                Cliente cliente = null;
                try {
                    cliente = ServicoCliente.procurarCliente(cpf);
                } catch (Exception ex) {
                    Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                String resposta = ServicoCliente.excluirCliente(cliente.getIdCliente());

                if (resposta == null) {
                    JOptionPane.showMessageDialog(null, "Cliente excluido com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(null, resposta);
                }

                try {
                    popularTabela(null);
                } catch (Exception ex) {
                    Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_buttonDeletarActionPerformed

    public void alterar() throws Exception {
        if (jTableClientesCadsatrados.getSelectedRow() >= 0) {
            final int row = jTableClientesCadsatrados.getSelectedRow();
            String cpf = (String) jTableClientesCadsatrados.getValueAt(row, 2);
            Cliente cliente = ServicoCliente.procurarCliente(cpf);
            if (cliente != null) {
                incluirCliente.dispose();
                incluirCliente = new IncluirCliente();
                incluirCliente.setCliente(cliente);
                incluirCliente.setModoEdicao(true);
                incluirCliente.setTitle("Alterar dados, " + cliente.getNome()
                        + " " + cliente.getSobrenome());
                this.getParent().add(incluirCliente);
                incluirCliente.setVisible(true);
                incluirCliente.toFront();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não foi pré selecionado"
                        + " um cliente para edicao",
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        try {
            alterar();
        } catch (Exception ex) {
            Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void fieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCpfActionPerformed
        
    }//GEN-LAST:event_fieldCpfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TabelaCliente;
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonDeletar;
    private javax.swing.JToggleButton buttonPesquisa;
    private javax.swing.JTextField fieldCpf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTableClientesCadsatrados;
    private javax.swing.JLabel lblCpfPesquisa;
    private javax.swing.JLabel lblPesquisaClientes;
    // End of variables declaration//GEN-END:variables

    private void openFrameInCenter(IncluirCliente incluirCliente) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
