/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoPoo.telas.funcionario;

import br.com.projetoPoo.model.pessoa.funcionario.Funcionario;
import br.com.projetoPoo.servico.ServicoFuncionario;
import br.com.projetoPoo.telas.cliente.PesquisarCliente;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raul de Paula
 */
public class PesquisarFuncionario extends javax.swing.JInternalFrame {

    IncluirFuncionario incluirFuncionario = new IncluirFuncionario();

    /**
     * Creates new form PesquisarCliente
     */
    public PesquisarFuncionario() throws Exception {
        initComponents();
        popularTabela(null, "Ativos");
        lblCpfPesquisa.setVisible(false);
        fieldCpf.setVisible(false);
        buttonPesquisa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabelaCliente = new javax.swing.JScrollPane();
        jTableClientesCadsatrados = new javax.swing.JTable();
        lblPesquisaClientes = new javax.swing.JLabel();
        lblCpfPesquisa = new javax.swing.JLabel();
        buttonPesquisa = new javax.swing.JToggleButton();
        buttonAlterar = new javax.swing.JButton();
        buttonDeletar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        fieldCpf = new javax.swing.JTextField();
        lblTipoPesquisa = new javax.swing.JLabel();
        boxTipoPesquisa = new javax.swing.JComboBox<>();
        buttonTipoPesquisa = new javax.swing.JToggleButton();

        jPanel1.setBackground(new java.awt.Color(240, 240, 255));

        jTableClientesCadsatrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome Completo", "CPF", "Dt Nascimento", "RG", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaCliente.setViewportView(jTableClientesCadsatrados);

        lblPesquisaClientes.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        lblPesquisaClientes.setText("Pesquisa de Funcionario");

        lblCpfPesquisa.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lblCpfPesquisa.setText("CPF de Pesquisa");

        buttonPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa 1.png"))); // NOI18N
        buttonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisaActionPerformed(evt);
            }
        });

        buttonAlterar.setText("Alterar");
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        buttonDeletar.setText("Deletar");
        buttonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        fieldCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCpfFocusLost(evt);
            }
        });
        fieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCpfActionPerformed(evt);
            }
        });

        lblTipoPesquisa.setText("Pesquisar por:");

        boxTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Cpf", "Todos", "Ativos", "Negativos" }));
        boxTipoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoPesquisaActionPerformed(evt);
            }
        });

        buttonTipoPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa 1.png"))); // NOI18N
        buttonTipoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTipoPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCpfPesquisa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(buttonCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonDeletar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonAlterar))
                        .addComponent(TabelaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPesquisaClientes)
                    .addComponent(lblTipoPesquisa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPesquisaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipoPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCpfPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabelaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAlterar)
                    .addComponent(buttonDeletar)
                    .addComponent(buttonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popularTabela(String cpf, String ativos) throws Exception {

        List<Funcionario> listaFuncionarios = null;
        try {
            switch (ativos) {
                case "todos":
                    listaFuncionarios = ServicoFuncionario.listar();
                    break;
                case "Ativos":
                    listaFuncionarios = ServicoFuncionario.listarPorStatus(true);
                    break;
                case "Negativos":
                    listaFuncionarios = ServicoFuncionario.listarPorStatus(false);
                    break;
                default:
                    listaFuncionarios = ServicoFuncionario.listar();
                    break;
            }
        } catch (Exception ex) {
            Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        Funcionario funcionario;
        DefaultTableModel dtmClientes = (DefaultTableModel) jTableClientesCadsatrados.getModel();
        Object[] dados = new Object[6];
        dtmClientes.setRowCount(0);
        if (cpf != null && !cpf.equals("")) {
            dtmClientes.setRowCount(0);
            funcionario = ServicoFuncionario.obterUm(cpf);
            dados[0] = funcionario.getCodFuncionario();
            dados[1] = funcionario.getNome() + " " + funcionario.getSobrenome();
            dados[2] = funcionario.getCpf();
            dados[3] = funcionario.getDataNascimento();
            dados[4] = funcionario.getRg();
            dados[5] = funcionario.getUsuario();

            dtmClientes.addRow(dados);
        } else {
            dtmClientes.setRowCount(0);
            int contadorPosicao = 0;
            while (listaFuncionarios != null && contadorPosicao < listaFuncionarios.size()) {
                funcionario = listaFuncionarios.get(contadorPosicao);
                dados[0] = funcionario.getCodFuncionario();
                dados[1] = funcionario.getNome() + " " + funcionario.getSobrenome();
                dados[2] = funcionario.getCpf();
                dados[3] = funcionario.getDataNascimento();
                dados[4] = funcionario.getRg();
                dados[5] = funcionario.getUsuario();

                dtmClientes.addRow(dados);
                contadorPosicao++;
            }
        }
    }

    private void buttonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisaActionPerformed
        if (fieldCpf.getText() != null && !fieldCpf.getText().equals("")) {
            try {
                String cpf = "";
                cpf += fieldCpf.getText().substring(0, 3)
                        + fieldCpf.getText().substring(4, 7)
                        + fieldCpf.getText().substring(8, 11)
                        + fieldCpf.getText().substring(12, 14);
                popularTabela(cpf, "todos");
                lblCpfPesquisa.setVisible(false);
                fieldCpf.setVisible(false);
                buttonPesquisa.setVisible(false);

                lblTipoPesquisa.setVisible(true);
                boxTipoPesquisa.setVisible(true);
                buttonTipoPesquisa.setVisible(true);
                
            } catch (Exception ex) {
                Logger.getLogger(PesquisarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (fieldCpf.getText().equals("")) {
            try {
                popularTabela(null, "Ativos");
                lblCpfPesquisa.setVisible(false);
                fieldCpf.setVisible(false);
                buttonPesquisa.setVisible(false);

                lblTipoPesquisa.setVisible(true);
                boxTipoPesquisa.setVisible(true);
                buttonTipoPesquisa.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (fieldCpf.getText().length() != 14) {
            JOptionPane.showMessageDialog(rootPane, "Numero de CPF Inválido.");
        } else {
            try {
                popularTabela(null, "Ativos");
            } catch (Exception ex) {
                Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_buttonPesquisaActionPerformed

    public void alterar() throws Exception {
        if (jTableClientesCadsatrados.getSelectedRow() >= 0) {
            final int row = jTableClientesCadsatrados.getSelectedRow();
            String cpf = (String) jTableClientesCadsatrados.getValueAt(row, 2);
            Funcionario funcionario = ServicoFuncionario.obterUm(cpf);
            if (funcionario != null) {
                incluirFuncionario.dispose();
                incluirFuncionario = new IncluirFuncionario();
                incluirFuncionario.setFuncionario(funcionario);
                incluirFuncionario.setModoEdicao(true);
                incluirFuncionario.setTitle("Alterar dados, " + funcionario.getNome()
                        + " " + funcionario.getSobrenome());
                this.getParent().add(incluirFuncionario);
                incluirFuncionario.setVisible(true);
                incluirFuncionario.toFront();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não foi pré selecionado"
                        + " um funcionario para edicao",
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        try {
            alterar();
        } catch (Exception ex) {
            Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.dispose();
    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void buttonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletarActionPerformed

        if (jTableClientesCadsatrados.getSelectedRow() >= 0) {
            final int row = jTableClientesCadsatrados.getSelectedRow();
            String nome = (String) jTableClientesCadsatrados.getValueAt(row, 1);
            int respostaConfirmacao = JOptionPane.showConfirmDialog(rootPane,
                    "Excluir o funcionario \"" + nome + "\"?",
                    "Confirmar exclusão", JOptionPane.YES_NO_OPTION);
            if (respostaConfirmacao == JOptionPane.YES_OPTION) {
                String cpf = (String) jTableClientesCadsatrados.getValueAt(row, 2);
                String resposta = ServicoFuncionario.excluir(cpf);

                if (resposta == null) {
                    JOptionPane.showMessageDialog(null, "Funcionario excluido com sucesso.");
                    try {
                        popularTabela(null, "Ativos");
                    } catch (Exception ex) {
                        Logger.getLogger(PesquisarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, resposta);
                }

                try {
                    popularTabela(null, "Ativos");
                } catch (Exception ex) {
                    Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_buttonDeletarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void fieldCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCpfFocusGained
        buttonPesquisa.setEnabled(true);
        if (fieldCpf.getText() != null && fieldCpf.getText().length() != 14) {
            fieldCpf.setText(null);
            fieldCpf.setBorder(new LineBorder(Color.LIGHT_GRAY));
        }
    }//GEN-LAST:event_fieldCpfFocusGained

    private void fieldCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCpfFocusLost
        if (fieldCpf.getText().length() == 11) {
            String CPF = fieldCpf.getText();
            String CpfS = "";
            CpfS += CPF.substring(0, 3) + ".";
            CpfS += CPF.substring(3, 6) + ".";
            CpfS += CPF.substring(6, 9) + "-";
            CpfS += CPF.substring(9, 11);
            fieldCpf.setText(CpfS);
        } else if (fieldCpf.getText() != null && (fieldCpf.getText().length() > 11
                || fieldCpf.getText().length() < 11)) {
            fieldCpf.setBorder(new LineBorder(Color.RED));
        }
    }//GEN-LAST:event_fieldCpfFocusLost

    private void fieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCpfActionPerformed

    }//GEN-LAST:event_fieldCpfActionPerformed

    private void buttonTipoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTipoPesquisaActionPerformed
        String tipoPesquisa = (String) boxTipoPesquisa.getSelectedItem();
        if (tipoPesquisa.equals("Cpf")) {
            lblCpfPesquisa.setVisible(true);
            fieldCpf.setVisible(true);
            buttonPesquisa.setVisible(true);

            lblTipoPesquisa.setVisible(false);
            boxTipoPesquisa.setVisible(false);
            buttonTipoPesquisa.setVisible(false);
        } else if (tipoPesquisa.equals("Ativos")) {
            try {
                popularTabela(null, "Ativos");
            } catch (Exception ex) {
                Logger.getLogger(PesquisarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (tipoPesquisa.equals("Negativos")) {
            try {
                popularTabela(null, "Negativos");
            } catch (Exception ex) {
                Logger.getLogger(PesquisarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (tipoPesquisa.equals("Todos")) {
            try {
                popularTabela(null, "todos");
            } catch (Exception ex) {
                Logger.getLogger(PesquisarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonTipoPesquisaActionPerformed

    private void boxTipoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTipoPesquisaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TabelaCliente;
    private javax.swing.JComboBox<String> boxTipoPesquisa;
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonDeletar;
    private javax.swing.JToggleButton buttonPesquisa;
    private javax.swing.JToggleButton buttonTipoPesquisa;
    private javax.swing.JTextField fieldCpf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTableClientesCadsatrados;
    private javax.swing.JLabel lblCpfPesquisa;
    private javax.swing.JLabel lblPesquisaClientes;
    private javax.swing.JLabel lblTipoPesquisa;
    // End of variables declaration//GEN-END:variables
}
